require:
  - rubocop-rails
  - rubocop-rspec

inherit_from: ./lib/rubocop/blacklist.yml

AllCops:
  TargetRubyVersion: 3.0.2
  NewCops: enable

Layout/LineLength:
  Max: 110
  IgnoredPatterns: ['(\A|\s)#']

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'skip']
  Exclude:
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Lint/MissingSuper:
  Enabled: false

Rails/EnvironmentVariableAccess:
  Enabled: false

# rubocop-rspec gem excludes
RSpec/NamedSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 9

RSpec/DescribeClass:
  Exclude:
    - 'spec/api_wrappers/**/*.rb'
