require: rubocop-rails
inherit_from: ./lib/rubocop/blacklist.yml

AllCops:
  TargetRubyVersion: 2.6.3

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/LineLength:
  Max: 99
  IgnoredPatterns: ['\A#']

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Style/MixinUsage:
  Exclude:
    - 'features/step_definitions/*.rb'
